name: ai_photo_generator
description: AI Photo Generator using Flutter
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.3.0
  cached_network_image: ^3.4.1
  permission_handler: ^12.0.1
  image_gallery_saver_plus: ^4.0.1
  path_provider: ^2.1.5
  share_plus: ^11.1.0
  flutter_animate: ^4.5.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true